### ISSUE TITLE
WM actions?

### ISSUE THREAD

**Issue by krsna-m** [dreinharth/byway#3]
Is there a plan for window close, toggle maximize (not same as fullscreen), snap window to side/top,etc. ?

**Comment by dreinharth** [comment]
> window close
That sounds like a good idea, I'll add that to the roadmap

> toggle maximize (not same as fullscreen)
I understand that's not the same as fullscreen from the app perspective, but I think it is the same as fullscreen currently implemented in byway, where the toplevel is simply set to take up the entire screen (independent of app fullscreen).  Is that accurate?

> snap window to side/top,etc.
No plans at this point for more complex toplevel placement, but possibly in the future
