### ISSUE TITLE
Can't cycle windows with same app_id.

### ISSUE THREAD

**Issue by ahmadraniri1994** [dreinharth/byway#5]
I just realised that windows with same app_id, e.g I open 3 terminal windows (foot), can't be cycled. When there is another window with different app_id (e.g lximage), it can be cycled but only one foot terminal window and one lximage window, the other 2 foot windows are ignored.

**Comment by dreinharth** [comment]
Are you using `cycle_toplevels` vs. `cycle_groups`?  In the example [config](https://github.com/dreinharth/byway/blob/main/config.json.example#L114-L137), `Alt + Tab` cycles among groups, and `Alt + ~` cycles among toplevels within a group.

**Comment by ahmadraniri1994** [comment]
Both is quite same for me, I open 3 windows (2 identical terminals and lximage). When I use cycle_groups, it only cycle between one terminal window and lximage. When I use cycle_toplevels, it only cycle between terminal windows.
Any alternative to cycle all windows ?

**Comment by dreinharth** [comment]
The current intent is to keep those actions distinct (cycle among groups vs. cycle among toplevels within a group).  If you would like to cycle among all toplevels regardless of app_id, that should be a quick patch:

1. Delete [these lines](https://github.com/dreinharth/byway/blob/2f3506284ad3e685fb82b739e9e5e38fbb290775/src/main.zig#L2655-L2661)
2. Change `app_id_comp` in [this line](https://github.com/dreinharth/byway/blob/2f3506284ad3e685fb82b739e9e5e38fbb290775/src/main.zig#L2640) to `_`  (single underscore character)
3. Rebuild/reinstall

With that change, both `cycle_groups` and `cycle_toplevels` should cycle all toplevels regardless of group.

**Comment by ahmadraniri1994** [comment]
Thanks @dreinharth, I'll try it later.

**Comment by ahmadraniri1994** [comment]
I guess stick to default one is fine, thanks.

**Comment by ahmadraniri1994** [comment]
I decided to make new function (rather than remove or change the existing one) according to your advice and it works. Thanks @dreinharth .
